# Generated by Django 2.1.2 on 2018-10-03 14:18

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todoitem',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 3, 14, 18, 12, 1880, tzinfo=utc), verbose_name='date created'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='todoitem',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 3, 14, 18, 24, 78700, tzinfo=utc), verbose_name='due date'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='todolist',
            name='completed',
            field=models.IntegerField(default=0),
        ),
    ]
